import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedMonishaBahugunaWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedImage12Widget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedKooBlackIcon300x300Copy1Widget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedEmailceoihubiitmandiinWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedRectangle1Widget31.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedBytesizemenuWidget23.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedEmailfmobasherah111gmailcomWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedFrame51Widget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedFabrandstwittersquareWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedChiefExecutiveOfficerWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/Generated919015458338Widget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedTeamWidget11.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedMrAvinashPunekarCEOIITMandiiHubandHCIFoundationWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedFabasherahMalakWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedBrandicolinkedinrectWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedFrame28Widget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedEmailmfabasherahgmailcomWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedImage9Widget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedDollyChoudharyWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedGiveusyourfeedbackhereWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedImage8Widget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedContactWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedEmaildollychoudhary220gmailcomWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedAppDevelopersWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedImage11Widget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedBrandicoinstagramfilledWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedEmaildollychoudhary220gmailcomWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedEmailmonishaihubiitmandiinWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedImage10Widget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedBrandicofacebookrectWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedConnectwithusWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedDollyChoudharyWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedEmailmfabasherahgmailcomWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedAssociatePROutreachWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox43widget/generated/GeneratedMobasherahFalakWidget2.dart';

/* Frame iPhone 11 Pro / X - 43
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX43Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 594.0,
                right: -2.0,
                bottom: null,
                width: null,
                height: 341.0,
                child: GeneratedRectangle16Widget1(),
              ),
              Positioned(
                left: -1.0,
                top: 218.0,
                right: -2.0,
                bottom: null,
                width: null,
                height: 338.0,
                child: GeneratedRectangle17Widget1(),
              ),
              Positioned(
                left: 22.0,
                top: 234.0,
                right: 66.0,
                bottom: null,
                width: null,
                height: 16.0,
                child: GeneratedChiefExecutiveOfficerWidget4(),
              ),
              Positioned(
                left: 194.0,
                top: 407.0,
                right: -106.0,
                bottom: null,
                width: null,
                height: 16.0,
                child: GeneratedAssociatePROutreachWidget2(),
              ),
              Positioned(
                left: 26.0,
                top: 599.0,
                right: 62.0,
                bottom: null,
                width: null,
                height: 23.0,
                child: GeneratedAppDevelopersWidget3(),
              ),
              Positioned(
                left: 23.0,
                top: 279.0,
                right: 34.0,
                bottom: null,
                width: null,
                height: 44.0,
                child:
                    GeneratedMrAvinashPunekarCEOIITMandiiHubandHCIFoundationWidget3(),
              ),
              Positioned(
                left: 194.0,
                top: 469.0,
                right: -140.0,
                bottom: null,
                width: null,
                height: 38.0,
                child: GeneratedEmailmonishaihubiitmandiinWidget2(),
              ),
              Positioned(
                left: 194.0,
                top: 443.0,
                right: -137.0,
                bottom: null,
                width: null,
                height: 16.0,
                child: GeneratedMonishaBahugunaWidget2(),
              ),
              Positioned(
                left: 25.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child: GeneratedEmailceoihubiitmandiinWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: null,
                width: 85.0,
                height: 84.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 473.00, z: 0, child: GeneratedImage8Widget4()),
              ),
              Positioned(
                left: null,
                top: null,
                right: 18.975547790527344,
                bottom: null,
                width: 77.27371978759766,
                height: 82.16021728515625,
                child: TransformHelper.translate(
                    x: 0.00, y: 376.08, z: 0, child: GeneratedImage9Widget4()),
              ),
              Positioned(
                left: null,
                top: 252.0,
                right: 31.0,
                bottom: null,
                width: 87.0,
                height: 97.0,
                child: GeneratedImage10Widget4(),
              ),
              Positioned(
                left: 34.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 92.0,
                child: GeneratedImage11Widget4(),
              ),
              Positioned(
                left: 18.0,
                top: 643.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 83.0,
                child: GeneratedImage12Widget4(),
              ),
              Positioned(
                left: 190.0,
                top: 673.0,
                right: -133.0,
                bottom: null,
                width: null,
                height: 16.0,
                child: GeneratedMobasherahFalakWidget2(),
              ),
              Positioned(
                left: 10.0,
                top: 767.0,
                right: 47.0,
                bottom: null,
                width: null,
                height: 16.0,
                child: GeneratedFabasherahMalakWidget2(),
              ),
              Positioned(
                left: 190.0,
                top: 860.0,
                right: -133.0,
                bottom: null,
                width: null,
                height: 16.0,
                child: GeneratedDollyChoudharyWidget2(),
              ),
              Positioned(
                left: 186.0,
                top: 706.0,
                right: -140.0,
                bottom: null,
                width: null,
                height: 26.0,
                child: GeneratedEmailfmobasherah111gmailcomWidget2(),
              ),
              Positioned(
                left: 13.0,
                top: 797.0,
                right: 41.0,
                bottom: null,
                width: null,
                height: 29.0,
                child: GeneratedEmailmfabasherahgmailcomWidget2(),
              ),
              Positioned(
                left: 186.0,
                top: 886.0,
                right: -141.0,
                bottom: null,
                width: null,
                height: 26.0,
                child: GeneratedEmaildollychoudhary220gmailcomWidget3(),
              ),
              Positioned(
                left: -5.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 357.0002136230469,
                height: 22.11505126953125,
                child: GeneratedFrame51Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0746666666666667;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.015999998728434245,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget31(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: GeneratedBytesizemenuWidget23(),
              ),
              Positioned(
                left: -3.0,
                top: 1214.0,
                right: null,
                bottom: null,
                width: 381.0,
                height: 312.0,
                child: GeneratedRectangle2Widget2(),
              ),
              Positioned(
                left: 152.0,
                top: 152.0,
                right: 155.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedTeamWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 1008.0,
                right: null,
                bottom: null,
                width: 368.0,
                height: 37.0,
                child: GeneratedGiveusyourfeedbackhereWidget2(),
              ),
              Positioned(
                left: 17.0,
                top: 1233.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 60.0,
                child:
                    GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK2(),
              ),
              Positioned(
                left: 294.0,
                top: 1456.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 55.0,
                child: GeneratedBrandicolinkedinrectWidget2(),
              ),
              Positioned(
                left: 221.0,
                top: 1459.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 51.0,
                child: GeneratedBrandicofacebookrectWidget2(),
              ),
              Positioned(
                left: 153.0,
                top: 1457.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 55.0,
                child: GeneratedBrandicoinstagramfilledWidget2(),
              ),
              Positioned(
                left: 81.0,
                top: 1454.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 60.0,
                child: GeneratedFabrandstwittersquareWidget2(),
              ),
              Positioned(
                left: 117.0,
                top: 1423.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 23.0,
                child: GeneratedConnectwithusWidget2(),
              ),
              Positioned(
                left: 15.0,
                top: 1359.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 26.0,
                child: GeneratedContactWidget2(),
              ),
              Positioned(
                left: 93.0,
                top: 1359.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 23.0,
                child: Generated919015458338Widget2(),
              ),
              Positioned(
                left: 14.0,
                top: 1454.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 56.0,
                child: GeneratedKooBlackIcon300x300Copy1Widget2(),
              ),
              Positioned(
                left: 191.0,
                top: 859.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 35.0,
                child: GeneratedDollyChoudharyWidget3(),
              ),
              Positioned(
                left: 188.0,
                top: 809.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child: GeneratedEmailmfabasherahgmailcomWidget3(),
              ),
              Positioned(
                left: 189.0,
                top: 885.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 52.0,
                child: GeneratedEmaildollychoudhary220gmailcomWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 87.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 721.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7573333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.25333333333333335,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle34Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 110.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 694.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.84;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2693333333333333,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFrame28Widget6(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
