import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedLogoutWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedAddAdminWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedResponseWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedRectangle46Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedRectangle48Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedSettingWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedEosiconsadminWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedRectangle45Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedRectangle47Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedCategoryWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedPushnotificationWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedHomeWidget42.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedRectangle52Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedRectangle42Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedRectangle49Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedRectangle40Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedRectangle51Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedRectangle50Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedRectangle44Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedAddWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedRectangle41Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedContentWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedPanelsWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedCategoryWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox116widget/generated/GeneratedRectangle43Widget1.dart';

/* Frame iPhone 11 Pro / X - 116
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX116Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 84.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle40Widget1(),
              ),
              Positioned(
                left: 13.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle44Widget1(),
              ),
              Positioned(
                left: 159.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle41Widget1(),
              ),
              Positioned(
                left: 228.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle42Widget1(),
              ),
              Positioned(
                left: 303.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle43Widget1(),
              ),
              Positioned(
                left: 114.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle45Widget1(),
              ),
              Positioned(
                left: 208.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle46Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 109.0,
                right: 301.0,
                bottom: null,
                width: null,
                height: 14.0,
                child: GeneratedHomeWidget42(),
              ),
              Positioned(
                left: 165.0,
                top: 107.0,
                right: 154.0,
                bottom: null,
                width: null,
                height: 14.0,
                child: GeneratedCategoryWidget2(),
              ),
              Positioned(
                left: 93.0,
                top: 107.0,
                right: 226.0,
                bottom: null,
                width: null,
                height: 14.0,
                child: GeneratedPanelsWidget1(),
              ),
              Positioned(
                left: 245.0,
                top: 108.0,
                right: 95.0,
                bottom: null,
                width: null,
                height: 14.0,
                child: GeneratedAddWidget1(),
              ),
              Positioned(
                left: 114.0,
                top: 148.0,
                right: 199.0,
                bottom: null,
                width: null,
                height: 11.0,
                child: GeneratedAddAdminWidget1(),
              ),
              Positioned(
                left: 314.0,
                top: 107.0,
                right: 7.0,
                bottom: null,
                width: null,
                height: 14.0,
                child: GeneratedSettingWidget1(),
              ),
              Positioned(
                left: 219.0,
                top: 148.0,
                right: 102.0,
                bottom: null,
                width: null,
                height: 14.0,
                child: GeneratedLogoutWidget1(),
              ),
              Positioned(
                left: 149.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedEosiconsadminWidget1(),
              ),
              Positioned(
                left: 39.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 342.0,
                child: GeneratedRectangle47Widget1(),
              ),
              Positioned(
                left: 64.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 91.0,
                child: GeneratedRectangle49Widget1(),
              ),
              Positioned(
                left: 64.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 91.0,
                child: GeneratedRectangle51Widget1(),
              ),
              Positioned(
                left: 200.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 91.0,
                child: GeneratedRectangle50Widget1(),
              ),
              Positioned(
                left: 200.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 91.0,
                child: GeneratedRectangle52Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 50.0,
                child: GeneratedRectangle48Widget1(),
              ),
              Positioned(
                left: 216.0,
                top: 354.0,
                right: 94.0,
                bottom: null,
                width: null,
                height: 16.0,
                child: GeneratedCategoryWidget3(),
              ),
              Positioned(
                left: 227.0,
                top: 478.0,
                right: 83.0,
                bottom: null,
                width: null,
                height: 16.0,
                child: GeneratedResponseWidget1(),
              ),
              Positioned(
                left: 69.0,
                top: 351.0,
                right: 241.0,
                bottom: null,
                width: null,
                height: 16.0,
                child: GeneratedContentWidget1(),
              ),
              Positioned(
                left: 77.0,
                top: 467.0,
                right: 224.0,
                bottom: null,
                width: null,
                height: 13.0,
                child: GeneratedPushnotificationWidget1(),
              )
            ]),
      ),
    ));
  }
}
