import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox115widget/generated/GeneratedYourresponsehasbeensubmittedWidget.dart';

/* Frame iPhone 11 Pro / X - 115
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX115Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 97.0,
                top: 358.0,
                right: 95.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedYourresponsehasbeensubmittedWidget(),
              )
            ]),
      ),
    ));
  }
}
