import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedIonchevronbackcircleWidget16.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedIonchevronbackcircleWidget15.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedIonchevronbackcircleWidget14.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedRubiscape1Widget3.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedNeuroleap1Widget3.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedCatalystWidget3.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedNeuroleapWidget3.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedIonchevronbackcircleWidget17.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedCatalyst1Widget3.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedITRAWidget3.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedRubiscapeWidget2.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedItra1Widget3.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedIonchevronbackcircleWidget18.dart';
import 'package:flutterapp/mopoapp/generatedframe27widget/generated/GeneratedIonchevronbackcircleWidget19.dart';

/* Frame Frame 27
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame27Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Container(
              width: 1766.0,
              child: Stack(children: [
                Container(
                    height: constraints.maxHeight,
                    child: Container(
                      width: 1766.0,
                      height: 351.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 0, 0, 0),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 482.0,
                              height: 276.0,
                              child: GeneratedRubiscape1Widget3(),
                            ),
                            Positioned(
                              left: 535.0,
                              top: 16.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 250.0,
                              child: GeneratedItra1Widget3(),
                            ),
                            Positioned(
                              left: 1391.0,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 244.0,
                              child: GeneratedCatalyst1Widget3(),
                            ),
                            Positioned(
                              left: 963.0,
                              top: 10.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 231.0,
                              child: GeneratedNeuroleap1Widget3(),
                            ),
                            Positioned(
                              left: 1056.0,
                              top: 257.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 60.0,
                              child: GeneratedNeuroleapWidget3(),
                            ),
                            Positioned(
                              left: 1484.0,
                              top: 269.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 60.0,
                              child: GeneratedCatalystWidget3(),
                            ),
                            Positioned(
                              left: 608.0,
                              top: 269.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 60.0,
                              child: GeneratedITRAWidget3(),
                            ),
                            Positioned(
                              left: 192.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 60.0,
                              child: GeneratedRubiscapeWidget2(),
                            ),
                            Positioned(
                              left: 1338.0,
                              top: 113.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget14(),
                            ),
                            Positioned(
                              left: 915.0,
                              top: 163.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget15(),
                            ),
                            Positioned(
                              left: 487.0,
                              top: 175.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget16(),
                            ),
                            Positioned(
                              left: 535.0,
                              top: 120.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget17(),
                            ),
                            Positioned(
                              left: 963.0,
                              top: 63.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget18(),
                            ),
                            Positioned(
                              left: 1386.0,
                              top: 133.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget19(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
