import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedGM1Widget5.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedPostDoctoralFellowshipWidget5.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedIonchevronbackcircleWidget72.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedAnubhavFellowshipWidget5.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedIonchevronbackcircleWidget71.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedIonchevronbackcircleWidget73.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedCFP1Widget3.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedAnubhav1Widget5.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedPostDoc1Widget5.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedIonchevronbackcircleWidget75.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedIonchevronbackcircleWidget74.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedRecruitmentWidget10.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedCallForProposalWidget3.dart';
import 'package:flutterapp/mopoapp/generatedframe25widget/generated/GeneratedIonchevronbackcircleWidget76.dart';

/* Frame Frame 25
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame25Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Container(
              width: 1696.0,
              child: Stack(children: [
                Container(
                    height: constraints.maxHeight,
                    child: Container(
                      width: 1696.0,
                      height: 550.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 0, 0, 0),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 1321.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 508.0,
                              child: GeneratedCFP1Widget3(),
                            ),
                            Positioned(
                              left: 868.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 199.0,
                              child: GeneratedAnubhav1Widget5(),
                            ),
                            Positioned(
                              left: 441.0,
                              top: 122.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 198.0,
                              child: GeneratedPostDoc1Widget5(),
                            ),
                            Positioned(
                              left: 175.0,
                              top: 358.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 31.0,
                              child: GeneratedRecruitmentWidget10(),
                            ),
                            Positioned(
                              left: 561.0,
                              top: 347.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedPostDoctoralFellowshipWidget5(),
                            ),
                            Positioned(
                              left: 998.0,
                              top: 343.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedAnubhavFellowshipWidget5(),
                            ),
                            Positioned(
                              left: 1464.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedCallForProposalWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 108.0,
                              right: null,
                              bottom: null,
                              width: 400.0,
                              height: 227.0,
                              child: GeneratedGM1Widget5(),
                            ),
                            Positioned(
                              left: 1325.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget71(),
                            ),
                            Positioned(
                              left: 835.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget72(),
                            ),
                            Positioned(
                              left: 441.0,
                              top: 188.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget73(),
                            ),
                            Positioned(
                              left: 400.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget74(),
                            ),
                            Positioned(
                              left: 816.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget75(),
                            ),
                            Positioned(
                              left: 1243.0,
                              top: 250.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget76(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
