import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedHomeWidget24.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedPostDoc1Widget7.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedAnubhavFellowshipWidget7.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedGM1Widget7.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedAkariconscirclechevronleftfillWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedDetailshttpsiitmandiacinacademicsfilesAnubhav20Fellowsh4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedTeamWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedIonchevronbackcircleWidget87.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedCallForProposalWidget5.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedAnubhav1Widget7.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedCFP1Widget5.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedDetailshttpsiitmandiacinadministrationadvrtadvt_GM_tih_3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedAnubhavFellowshipProgramWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedProjectsWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedPostDoctoralFellowshipsWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedCFPWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedHttpsiitmandiacinadministrationadvrtproposal_AI_ML_Dec23.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedRectangle29Widget5.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedIonchevronbackcircleWidget88.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedGeneralProjectManagerApplicationsareinvitedforthepostof3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedRectangle1Widget24.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedNMICPSWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedAboutUsWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedFacultyFellowshipProgramWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedRecruitmentWidget13.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedIonchevronbackcircleWidget85.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedDetailshttpsiitmandiacinacademicsfilespost20doc20fellow4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedIonchevronbackcircleWidget83.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedDetailshttpsiitmandiacinadministrationadvrtihub_faculty3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedIonchevronbackcircleWidget86.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedContactUsWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedCallForProposalsWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedFeedbackWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedPostDoctoralFellowshipWidget7.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedRecruitmentWidget12.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedIonchevronbackcircleWidget84.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox47widget/generated/GeneratedCarbonoverflowmenuverticalWidget20.dart';

/* Frame iPhone 11 Pro / X - 47
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX47Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 123.0,
                top: 158.0,
                right: 108.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedRecruitmentWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0426666666666666;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget24(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 20.0,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedCarbonoverflowmenuverticalWidget20(),
              ),
              Positioned(
                left: 34.0,
                top: 1027.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedFacultyFellowshipProgramWidget3(),
              ),
              Positioned(
                left: 43.0,
                top: 1114.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedPostDoctoralFellowshipsWidget3(),
              ),
              Positioned(
                left: 39.0,
                top: 1061.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedDetailshttpsiitmandiacinadministrationadvrtihub_faculty3(),
              ),
              Positioned(
                left: 34.0,
                top: 773.0,
                right: 26.0,
                bottom: null,
                width: null,
                height: 67.0,
                child:
                    GeneratedGeneralProjectManagerApplicationsareinvitedforthepostof3(),
              ),
              Positioned(
                left: 34.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 59.0,
                child:
                    GeneratedDetailshttpsiitmandiacinadministrationadvrtadvt_GM_tih_3(),
              ),
              Positioned(
                left: 88.0,
                top: 941.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 40.0,
                child: GeneratedProjectsWidget3(),
              ),
              Positioned(
                left: 44.0,
                top: 1143.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedDetailshttpsiitmandiacinacademicsfilespost20doc20fellow4(),
              ),
              Positioned(
                left: 47.0,
                top: 1196.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedAnubhavFellowshipProgramWidget3(),
              ),
              Positioned(
                left: 47.0,
                top: 1228.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedDetailshttpsiitmandiacinacademicsfilesAnubhav20Fellowsh4(),
              ),
              Positioned(
                left: 128.0,
                top: 1306.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 40.0,
                child: GeneratedCFPWidget3(),
              ),
              Positioned(
                left: 47.0,
                top: 1366.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedCallForProposalsWidget3(),
              ),
              Positioned(
                left: 47.0,
                top: 1393.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 55.0,
                child:
                    GeneratedHttpsiitmandiacinadministrationadvrtproposal_AI_ML_Dec23(),
              ),
              Positioned(
                left: 1296.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 508.0,
                child: GeneratedCFP1Widget5(),
              ),
              Positioned(
                left: 843.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 199.0,
                child: GeneratedAnubhav1Widget7(),
              ),
              Positioned(
                left: 416.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 198.0,
                child: GeneratedPostDoc1Widget7(),
              ),
              Positioned(
                left: 150.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 31.0,
                child: GeneratedRecruitmentWidget13(),
              ),
              Positioned(
                left: 536.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 28.0,
                child: GeneratedPostDoctoralFellowshipWidget7(),
              ),
              Positioned(
                left: 973.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 28.0,
                child: GeneratedAnubhavFellowshipWidget7(),
              ),
              Positioned(
                left: 1439.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 28.0,
                child: GeneratedCallForProposalWidget5(),
              ),
              Positioned(
                left: -25.0,
                top: 225.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 227.0,
                child: GeneratedGM1Widget7(),
              ),
              Positioned(
                left: 1300.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget83(),
              ),
              Positioned(
                left: 810.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget84(),
              ),
              Positioned(
                left: 416.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget85(),
              ),
              Positioned(
                left: 375.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget86(),
              ),
              Positioned(
                left: 791.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget87(),
              ),
              Positioned(
                left: 1218.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget88(),
              ),
              Positioned(
                left: 0.0,
                top: 87.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 722.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6213333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle29Widget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: 160.0,
                bottom: 0.0,
                width: 50.0,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.17118226600985223,
                        z: 0,
                        child: Container(
                          height: height,
                          child:
                              GeneratedAkariconscirclechevronleftfillWidget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 25.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 28.0,
                child: GeneratedHomeWidget24(),
              ),
              Positioned(
                left: 23.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 25.0,
                child: GeneratedAboutUsWidget6(),
              ),
              Positioned(
                left: 23.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 28.0,
                child: GeneratedNMICPSWidget6(),
              ),
              Positioned(
                left: 19.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 25.0,
                child: GeneratedContactUsWidget6(),
              ),
              Positioned(
                left: 24.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 28.0,
                child: GeneratedFeedbackWidget6(),
              ),
              Positioned(
                left: 32.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 28.0,
                child: GeneratedTeamWidget6(),
              )
            ]),
      ),
    ));
  }
}
