import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedPostDoc1Widget2.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedAnubhav1Widget2.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedIonchevronbackcircleWidget56.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedGM1Widget2.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedIonchevronbackcircleWidget54.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedIonchevronbackcircleWidget58.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedIonchevronbackcircleWidget57.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedAnubhavFellowshipWidget2.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedCallForProposalWidget.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedIonchevronbackcircleWidget53.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedCFP1Widget.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedIonchevronbackcircleWidget55.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedRecruitmentWidget7.dart';
import 'package:flutterapp/mopoapp/generatedframe30widget/generated/GeneratedPostDoctoralFellowshipWidget2.dart';

/* Frame Frame 30
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame30Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Container(
              width: 1696.0,
              child: Stack(children: [
                Container(
                    height: constraints.maxHeight,
                    child: Container(
                      width: 1696.0,
                      height: 550.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 0, 0, 0),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 1321.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 508.0,
                              child: GeneratedCFP1Widget(),
                            ),
                            Positioned(
                              left: 868.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 199.0,
                              child: GeneratedAnubhav1Widget2(),
                            ),
                            Positioned(
                              left: 441.0,
                              top: 122.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 198.0,
                              child: GeneratedPostDoc1Widget2(),
                            ),
                            Positioned(
                              left: 175.0,
                              top: 358.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 31.0,
                              child: GeneratedRecruitmentWidget7(),
                            ),
                            Positioned(
                              left: 561.0,
                              top: 347.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedPostDoctoralFellowshipWidget2(),
                            ),
                            Positioned(
                              left: 998.0,
                              top: 343.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedAnubhavFellowshipWidget2(),
                            ),
                            Positioned(
                              left: 1464.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedCallForProposalWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 108.0,
                              right: null,
                              bottom: null,
                              width: 400.0,
                              height: 227.0,
                              child: GeneratedGM1Widget2(),
                            ),
                            Positioned(
                              left: 1325.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget53(),
                            ),
                            Positioned(
                              left: 865.0,
                              top: 201.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget54(),
                            ),
                            Positioned(
                              left: 441.0,
                              top: 188.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget55(),
                            ),
                            Positioned(
                              left: 400.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget56(),
                            ),
                            Positioned(
                              left: 816.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget57(),
                            ),
                            Positioned(
                              left: 1243.0,
                              top: 250.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget58(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
