import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedRectangle2Widget22.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedFabrandstwittersquareWidget17.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedDropyourcommenthereWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedEnteryourfeedbackWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedBrandicolinkedinrectWidget17.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedBrandicofacebookrectWidget17.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/Generated919015458338Widget14.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedBrandicoinstagramfilledWidget17.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedFrame28Widget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedKooBlackIcon300x300Copy1Widget17.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedWritetousWidget5.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedFeedbackWidget16.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedRectangle15Widget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedContactWidget14.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK14.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedTihiitmandiacinWidget5.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedBytesizemenuWidget33.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedRectangle2Widget21.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedRectangle1Widget46.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedRectangle36Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedConnectwithusWidget17.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedEnteryourmailIDWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox44widget/generated/GeneratedSubmitWidget5.dart';

/* Frame iPhone 11 Pro / X - 44
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX44Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.048;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget46(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: GeneratedBytesizemenuWidget33(),
              ),
              Positioned(
                left: 0.0,
                top: 643.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 312.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle2Widget21(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 29.0,
                top: 217.0,
                right: 62.0,
                bottom: null,
                width: null,
                height: 31.0,
                child: GeneratedWritetousWidget5(),
              ),
              Positioned(
                left: 26.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 22.0,
                child: GeneratedDropyourcommenthereWidget2(),
              ),
              Positioned(
                left: 102.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 15.0,
                child: GeneratedTihiitmandiacinWidget5(),
              ),
              Positioned(
                left: 103.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 40.0,
                child: GeneratedFeedbackWidget16(),
              ),
              Positioned(
                left: 17.0,
                top: 673.0,
                right: 26.0,
                bottom: null,
                width: null,
                height: 92.0,
                child:
                    GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK14(),
              ),
              Positioned(
                left: 16.0,
                top: 336.0,
                right: 49.0,
                bottom: null,
                width: null,
                height: 119.0,
                child: GeneratedRectangle15Widget6(),
              ),
              Positioned(
                left: 16.0,
                top: 297.0,
                right: 49.0,
                bottom: null,
                width: null,
                height: 24.0,
                child: GeneratedRectangle36Widget1(),
              ),
              Positioned(
                left: 228.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 37.0,
                child: GeneratedSubmitWidget5(),
              ),
              Positioned(
                left: 200.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 33.0,
                child: GeneratedRectangle2Widget22(),
              ),
              Positioned(
                left: 297.0,
                top: 885.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 55.0,
                child: GeneratedBrandicolinkedinrectWidget17(),
              ),
              Positioned(
                left: 224.0,
                top: 888.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 51.0,
                child: GeneratedBrandicofacebookrectWidget17(),
              ),
              Positioned(
                left: 156.0,
                top: 886.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 55.0,
                child: GeneratedBrandicoinstagramfilledWidget17(),
              ),
              Positioned(
                left: 84.0,
                top: 883.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 60.0,
                child: GeneratedFabrandstwittersquareWidget17(),
              ),
              Positioned(
                left: 120.0,
                top: 852.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 23.0,
                child: GeneratedConnectwithusWidget17(),
              ),
              Positioned(
                left: 24.0,
                top: 788.0,
                right: 287.0,
                bottom: null,
                width: null,
                height: 23.0,
                child: GeneratedContactWidget14(),
              ),
              Positioned(
                left: 96.0,
                top: 788.0,
                right: 138.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: Generated919015458338Widget14(),
              ),
              Positioned(
                left: 17.0,
                top: 883.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 56.0,
                child: GeneratedKooBlackIcon300x300Copy1Widget17(),
              ),
              Positioned(
                left: 0.0,
                top: 87.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 721.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7573333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.25333333333333335,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle35Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 110.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 694.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.84;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2693333333333333,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFrame28Widget8(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 34.0,
                top: 303.0,
                right: 181.0,
                bottom: null,
                width: null,
                height: 15.0,
                child: GeneratedEnteryourmailIDWidget2(),
              ),
              Positioned(
                left: 29.0,
                top: 349.0,
                right: 186.0,
                bottom: null,
                width: null,
                height: 15.0,
                child: GeneratedEnteryourfeedbackWidget2(),
              )
            ]),
      ),
    ));
  }
}
