import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedPostDoctoralFellowshipWidget3.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedAnubhav1Widget3.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedPostDoc1Widget3.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedIonchevronbackcircleWidget63.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedIonchevronbackcircleWidget61.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedCallForProposalWidget1.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedGM1Widget3.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedIonchevronbackcircleWidget60.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedRecruitmentWidget8.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedIonchevronbackcircleWidget64.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedIonchevronbackcircleWidget59.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedIonchevronbackcircleWidget62.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedCFP1Widget1.dart';
import 'package:flutterapp/mopoapp/generatedframe23widget2/generated/GeneratedAnubhavFellowshipWidget3.dart';

/* Frame Frame 23
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame23Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Container(
              width: 6688.0,
              child: Stack(children: [
                Container(
                    height: constraints.maxHeight,
                    child: Container(
                      width: 1696.0,
                      height: 550.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 0, 0, 0),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 6313.0,
                              top: 368.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 508.0,
                              child: GeneratedCFP1Widget1(),
                            ),
                            Positioned(
                              left: 5860.0,
                              top: 489.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 199.0,
                              child: GeneratedAnubhav1Widget3(),
                            ),
                            Positioned(
                              left: 5433.0,
                              top: 490.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 198.0,
                              child: GeneratedPostDoc1Widget3(),
                            ),
                            Positioned(
                              left: 5167.0,
                              top: 726.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 31.0,
                              child: GeneratedRecruitmentWidget8(),
                            ),
                            Positioned(
                              left: 5553.0,
                              top: 715.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedPostDoctoralFellowshipWidget3(),
                            ),
                            Positioned(
                              left: 5990.0,
                              top: 711.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedAnubhavFellowshipWidget3(),
                            ),
                            Positioned(
                              left: 6456.0,
                              top: 890.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedCallForProposalWidget1(),
                            ),
                            Positioned(
                              left: 4992.0,
                              top: 476.0,
                              right: null,
                              bottom: null,
                              width: 400.0,
                              height: 227.0,
                              child: GeneratedGM1Widget3(),
                            ),
                            Positioned(
                              left: 6317.0,
                              top: 526.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget59(),
                            ),
                            Positioned(
                              left: 5857.0,
                              top: 569.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget60(),
                            ),
                            Positioned(
                              left: 5433.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget61(),
                            ),
                            Positioned(
                              left: 5392.0,
                              top: 613.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget62(),
                            ),
                            Positioned(
                              left: 5808.0,
                              top: 613.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget63(),
                            ),
                            Positioned(
                              left: 6235.0,
                              top: 618.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget64(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
