import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox90widget/generated/GeneratedIITmandi12Widget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox90widget/generated/GeneratedCatalystWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox90widget/generated/GeneratedMediaCoverageWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox90widget/generated/GeneratedFrame52Widget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox90widget/generated/GeneratedIonchevronbackcircleWidget7.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox90widget/generated/GeneratedCarbonoverflowmenuverticalWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox90widget/generated/GeneratedBytesizemenuWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox90widget/generated/GeneratedCatalyst1Widget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox90widget/generated/GeneratedIITMandiCatalysthaslaunchedincubationprogramstodevelops2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox90widget/generated/Generated4IITMandiiHubandHCIFoundationsignedMoUwithIITMandiCatal2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox90widget/generated/GeneratedRectangle1Widget8.dart';

/* Frame iPhone 11 Pro / X - 90
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX90Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1583.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1583.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 0, 0, 0),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 92.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.064;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * -0.016,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedRectangle1Widget8(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 24.0,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 36.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -740.50,
                                  z: 0,
                                  child: GeneratedBytesizemenuWidget6()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: 11.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -746.50,
                                  z: 0,
                                  child:
                                      GeneratedCarbonoverflowmenuverticalWidget6()),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 616.0,
                              right: 29.0,
                              bottom: null,
                              width: null,
                              height: 72.0,
                              child:
                                  GeneratedIITMandiCatalysthaslaunchedincubationprogramstodevelops2(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 546.0,
                              right: 60.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  Generated4IITMandiiHubandHCIFoundationsignedMoUwithIITMandiCatal2(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 155.0,
                              right: 75.0,
                              bottom: null,
                              width: null,
                              height: 31.0,
                              child: GeneratedMediaCoverageWidget2(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 244.0,
                              child: TransformHelper.translate(
                                  x: -3.00,
                                  y: -468.50,
                                  z: 0,
                                  child: GeneratedCatalyst1Widget2()),
                            ),
                            Positioned(
                              left: null,
                              top: 0.0,
                              right: null,
                              bottom: 0.0,
                              width: 193.0,
                              height: null,
                              child: TransformHelper.translate(
                                  x: -13.00,
                                  y: 0.00,
                                  z: 0,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double height =
                                        constraints.maxHeight *
                                            0.03790271636133923;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                          x: 0,
                                          y: constraints.maxHeight *
                                              0.2886923562855338,
                                          z: 0,
                                          child: Container(
                                            height: height,
                                            child: GeneratedCatalystWidget2(),
                                          ))
                                    ]);
                                  })),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 142.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget7(),
                            ),
                            Positioned(
                              left: -4.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 357.0002136230469,
                              height: 22.11505126953125,
                              child: GeneratedFrame52Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 65.0,
                              child: TransformHelper.translate(
                                  x: -2.50,
                                  y: -742.00,
                                  z: 0,
                                  child: GeneratedIITmandi12Widget()),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
