import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedAnubhavFellowshipWidget6.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedIonchevronbackcircleWidget80.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedCFP1Widget4.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedRecruitmentWidget11.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedPostDoctoralFellowshipWidget6.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedCallForProposalWidget4.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedIonchevronbackcircleWidget81.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedIonchevronbackcircleWidget82.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedIonchevronbackcircleWidget79.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedAnubhav1Widget6.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedIonchevronbackcircleWidget78.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedGM1Widget6.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedIonchevronbackcircleWidget77.dart';
import 'package:flutterapp/mopoapp/generatedframe26widget/generated/GeneratedPostDoc1Widget6.dart';

/* Frame Frame 26
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame26Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Container(
              width: 1696.0,
              child: Stack(children: [
                Container(
                    height: constraints.maxHeight,
                    child: Container(
                      width: 1696.0,
                      height: 550.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 0, 0, 0),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 1321.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 508.0,
                              child: GeneratedCFP1Widget4(),
                            ),
                            Positioned(
                              left: 868.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 199.0,
                              child: GeneratedAnubhav1Widget6(),
                            ),
                            Positioned(
                              left: 441.0,
                              top: 122.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 198.0,
                              child: GeneratedPostDoc1Widget6(),
                            ),
                            Positioned(
                              left: 175.0,
                              top: 358.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 31.0,
                              child: GeneratedRecruitmentWidget11(),
                            ),
                            Positioned(
                              left: 561.0,
                              top: 347.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedPostDoctoralFellowshipWidget6(),
                            ),
                            Positioned(
                              left: 998.0,
                              top: 343.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedAnubhavFellowshipWidget6(),
                            ),
                            Positioned(
                              left: 1464.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 28.0,
                              child: GeneratedCallForProposalWidget4(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 108.0,
                              right: null,
                              bottom: null,
                              width: 400.0,
                              height: 227.0,
                              child: GeneratedGM1Widget6(),
                            ),
                            Positioned(
                              left: 1325.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget77(),
                            ),
                            Positioned(
                              left: 835.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget78(),
                            ),
                            Positioned(
                              left: 441.0,
                              top: 188.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget79(),
                            ),
                            Positioned(
                              left: 400.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget80(),
                            ),
                            Positioned(
                              left: 816.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget81(),
                            ),
                            Positioned(
                              left: 1243.0,
                              top: 250.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget82(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
