import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedITRAWidget5.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedIonchevronbackcircleWidget26.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedCatalystWidget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedCarbonoverflowmenuverticalWidget12.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedIITmandi13Widget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedIonchevronbackcircleWidget31.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedIonchevronbackcircleWidget30.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedCatalyst1Widget5.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedNeuroleapWidget5.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedRectangle1Widget14.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedFrame49Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedFrame51Widget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedIonchevronbackcircleWidget27.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedNeuroleap1Widget5.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedItra1Widget5.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox89widget/generated/GeneratedIonchevronbackcircleWidget29.dart';

/* Frame iPhone 11 Pro / X - 89
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX89Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1650.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1650.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 0, 0, 0),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 92.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.056;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * -0.016,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedRectangle1Widget14(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: null,
                              top: 20.0,
                              right: 11.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child:
                                  GeneratedCarbonoverflowmenuverticalWidget12(),
                            ),
                            Positioned(
                              left: 427.0,
                              top: 196.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 250.0,
                              child: GeneratedItra1Widget5(),
                            ),
                            Positioned(
                              left: 1283.0,
                              top: 193.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 244.0,
                              child: GeneratedCatalyst1Widget5(),
                            ),
                            Positioned(
                              left: 855.0,
                              top: 190.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 231.0,
                              child: GeneratedNeuroleap1Widget5(),
                            ),
                            Positioned(
                              left: 948.0,
                              top: 437.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 60.0,
                              child: GeneratedNeuroleapWidget5(),
                            ),
                            Positioned(
                              left: 1376.0,
                              top: 449.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 60.0,
                              child: GeneratedCatalystWidget5(),
                            ),
                            Positioned(
                              left: 500.0,
                              top: 449.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 60.0,
                              child: GeneratedITRAWidget5(),
                            ),
                            Positioned(
                              left: 1230.0,
                              top: 293.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget26(),
                            ),
                            Positioned(
                              left: 807.0,
                              top: 343.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget27(),
                            ),
                            Positioned(
                              left: -108.0,
                              top: 117.0,
                              right: -177.0,
                              bottom: null,
                              width: null,
                              height: 1367.0,
                              child: GeneratedFrame49Widget1(),
                            ),
                            Positioned(
                              left: 427.0,
                              top: 300.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget29(),
                            ),
                            Positioned(
                              left: 855.0,
                              top: 243.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget30(),
                            ),
                            Positioned(
                              left: 1278.0,
                              top: 313.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget31(),
                            ),
                            Positioned(
                              left: -4.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 357.0002136230469,
                              height: 22.11505126953125,
                              child: GeneratedFrame51Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 65.0,
                              child: TransformHelper.translate(
                                  x: -2.50,
                                  y: -775.50,
                                  z: 0,
                                  child: GeneratedIITmandi13Widget()),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
