import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdsignMoU.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedITRACoLtdHeadquartersJapanTokyoRepresentativeDirectorKa.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedIITmandi4Widget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedToestablishstronglinkageswithnationalandinternationalor.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedRubiscapeWidget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedIITMandiiHubHCIFoundationIndiawwwihubiitmandiinandRubis.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedLinkhttpsdocsgooglecomspreadsheetsd1vp_ZtdmPoa2qDWwzcX0.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedIITMandiiHubHCIFoundationiHubWidget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedNeuroLeapWidget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedBytesizemenuWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/Generated3IITMandiiHubandHCIFoundationsignwiderangingMoUwithNeur.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedIITMandiCatalysthaslaunchedincubationprogramstodevelops.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedIonchevronbackcirclesharpWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/Generated4IITMandiiHubandHCIFoundationsignedMoUwithIITMandiCatal.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedMoUWidget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedMediaCoverageWidget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/Generated2IITMandiiHubHCIFoundationandITRACoLtdJapansignMoUWidge.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedRectangle1Widget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedRubiscape1Widget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedCarbonoverflowmenuverticalWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedHttpswwwiitmandiacinTIHHCIannoucementsphpWidget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedAndIndiahavesignedawiderangingMoUtoharnesseachothersstr.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox8widget/generated/GeneratedFrame48Widget.dart';

/* Frame iPhone 11 Pro / X - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1583.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1583.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 0, 0, 0),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 92.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0533333333333332;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * -0.016,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedRectangle1Widget6(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 24.0,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 36.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -740.50,
                                  z: 0,
                                  child: GeneratedBytesizemenuWidget4()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: 11.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -746.50,
                                  z: 0,
                                  child:
                                      GeneratedCarbonoverflowmenuverticalWidget4()),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 1434.0,
                              right: 19.0,
                              bottom: null,
                              width: null,
                              height: 72.0,
                              child:
                                  GeneratedIITMandiCatalysthaslaunchedincubationprogramstodevelops(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 1381.0,
                              right: 50.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  Generated4IITMandiiHubandHCIFoundationsignedMoUwithIITMandiCatal(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 1292.0,
                              right: 23.0,
                              bottom: null,
                              width: null,
                              height: 58.0,
                              child:
                                  GeneratedAndIndiahavesignedawiderangingMoUtoharnesseachothersstr(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 1240.0,
                              right: 53.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  Generated3IITMandiiHubandHCIFoundationsignwiderangingMoUwithNeur(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 1145.0,
                              right: 26.0,
                              bottom: null,
                              width: null,
                              height: 86.0,
                              child:
                                  GeneratedITRACoLtdHeadquartersJapanTokyoRepresentativeDirectorKa(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 923.0,
                              right: 62.0,
                              bottom: null,
                              width: null,
                              height: 30.0,
                              child:
                                  GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdsignMoU(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 1098.0,
                              right: 53.0,
                              bottom: null,
                              width: null,
                              height: 30.0,
                              child:
                                  Generated2IITMandiiHubHCIFoundationandITRACoLtdJapansignMoUWidge(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 848.0,
                              right: 28.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  GeneratedToestablishstronglinkageswithnationalandinternationalor(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 964.0,
                              right: 26.0,
                              bottom: null,
                              width: null,
                              height: 86.0,
                              child:
                                  GeneratedIITMandiiHubHCIFoundationIndiawwwihubiitmandiinandRubis(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 794.0,
                              right: 162.0,
                              bottom: null,
                              width: null,
                              height: 28.0,
                              child: GeneratedMoUWidget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 1289.0,
                              right: null,
                              bottom: null,
                              width: 318.0,
                              height: 55.0,
                              child: GeneratedNeuroLeapWidget(),
                            ),
                            Positioned(
                              left: 122.0,
                              top: 1293.0,
                              right: -62.0,
                              bottom: null,
                              width: null,
                              height: 52.0,
                              child:
                                  GeneratedIITMandiiHubHCIFoundationiHubWidget(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 711.0,
                              right: 18.0,
                              bottom: null,
                              width: null,
                              height: 19.0,
                              child:
                                  GeneratedHttpswwwiitmandiacinTIHHCIannoucementsphpWidget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 642.0,
                              right: 25.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  GeneratedLinkhttpsdocsgooglecomspreadsheetsd1vp_ZtdmPoa2qDWwzcX0(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 152.0,
                              right: 75.0,
                              bottom: null,
                              width: null,
                              height: 31.0,
                              child: GeneratedMediaCoverageWidget(),
                            ),
                            Positioned(
                              left: null,
                              top: 0.0,
                              right: null,
                              bottom: 0.0,
                              width: 193.0,
                              height: null,
                              child: TransformHelper.translate(
                                  x: -6.00,
                                  y: 0.00,
                                  z: 0,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double height =
                                        constraints.maxHeight *
                                            0.03790271636133923;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                          x: 0,
                                          y: constraints.maxHeight *
                                              0.32722678458622867,
                                          z: 0,
                                          child: Container(
                                            height: height,
                                            child: GeneratedRubiscapeWidget(),
                                          ))
                                    ]);
                                  })),
                            ),
                            Positioned(
                              left: -4.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 357.0002136230469,
                              height: 22.11505126953125,
                              child: GeneratedFrame48Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: 211.0,
                              right: 1.0,
                              bottom: null,
                              width: 482.0,
                              height: 276.0,
                              child: GeneratedRubiscape1Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: 408.0,
                              right: -38.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child:
                                  GeneratedIonchevronbackcirclesharpWidget1(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 65.0,
                              child: TransformHelper.translate(
                                  x: -2.50,
                                  y: -742.00,
                                  z: 0,
                                  child: GeneratedIITmandi4Widget()),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
