import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox42widget/generated/GeneratedNationalMissiononInterdisciplinaryCyberPhysicalSystemsN2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox42widget/generated/GeneratedBytesizemenuWidget21.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox42widget/generated/GeneratedRectangle1Widget28.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox42widget/generated/GeneratedNMICPSWidget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox42widget/generated/GeneratedFormorehttpsnmicpsgovinHomeICPSNMHOMEAboutusWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox42widget/generated/GeneratedMinistryofScienceTechnologyDeartmentofScienceTechnology2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox42widget/generated/GeneratedImage12Widget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox42widget/generated/GeneratedTeamhttpsnmicpsgovinHomeICPSNMHOMEMGBWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox42widget/generated/GeneratedNMICPSisacomprehensiveMissionaimedatcompleteconvergence2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox42widget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox42widget/generated/GeneratedFrame28Widget5.dart';

/* Frame iPhone 11 Pro / X - 42
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX42Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0533333333333332;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget28(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: GeneratedBytesizemenuWidget21(),
              ),
              Positioned(
                left: 24.0,
                top: 320.0,
                right: 36.0,
                bottom: null,
                width: null,
                height: 275.0,
                child:
                    GeneratedNMICPSisacomprehensiveMissionaimedatcompleteconvergence2(),
              ),
              Positioned(
                left: 30.0,
                top: 650.0,
                right: 30.0,
                bottom: null,
                width: null,
                height: 15.0,
                child:
                    GeneratedFormorehttpsnmicpsgovinHomeICPSNMHOMEAboutusWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 706.0,
                right: 30.0,
                bottom: null,
                width: null,
                height: 15.0,
                child: GeneratedTeamhttpsnmicpsgovinHomeICPSNMHOMEMGBWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 273.0,
                right: -60.0,
                bottom: null,
                width: null,
                height: 14.0,
                child:
                    GeneratedNationalMissiononInterdisciplinaryCyberPhysicalSystemsN2(),
              ),
              Positioned(
                left: 24.0,
                top: 284.0,
                right: 30.0,
                bottom: null,
                width: null,
                height: 26.0,
                child:
                    GeneratedMinistryofScienceTechnologyDeartmentofScienceTechnology2(),
              ),
              Positioned(
                left: 149.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 74.0,
                child: GeneratedImage12Widget2(),
              ),
              Positioned(
                left: 120.0,
                top: 139.0,
                right: 67.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedNMICPSWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 87.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 721.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7573333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.24533333333333332,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle33Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 110.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 694.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.84;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2693333333333333,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFrame28Widget5(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
