import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedIITmandi29Widget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/Generated919015458338Widget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedBrandicofacebookrectWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedFrame8Widget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedRectangle2Widget7.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedRectangle1Widget35.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedFabrandstwittersquareWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedCarbonoverflowmenuverticalWidget28.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedKooBlackIcon300x300Copy1Widget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedBytesizemenuWidget27.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedContactWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedBrandicolinkedinrectWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedBrandicoinstagramfilledWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedConnectwithusWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox76widget/generated/GeneratedFrame50Widget2.dart';

/* Frame iPhone 11 Pro / X - 76
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX76Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 956.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 955.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 0, 0, 0),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 92.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0746666666666667;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * -0.016,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedRectangle1Widget35(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 33.0,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 36.0,
                              child: GeneratedBytesizemenuWidget27(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: 11.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -432.50,
                                  z: 0,
                                  child:
                                      GeneratedCarbonoverflowmenuverticalWidget28()),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 151.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 804.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.016;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedFrame8Widget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: -3.02392578125,
                              top: 644.0,
                              right: -6.024078369140625,
                              bottom: null,
                              width: null,
                              height: 312.0,
                              child: GeneratedRectangle2Widget7(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 663.0,
                              right: 18.0,
                              bottom: null,
                              width: null,
                              height: 92.0,
                              child:
                                  GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK6(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 61.0,
                              height: 55.0,
                              child: TransformHelper.translate(
                                  x: 140.00,
                                  y: 436.00,
                                  z: 0,
                                  child:
                                      GeneratedBrandicolinkedinrectWidget6()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 51.0,
                              child: TransformHelper.translate(
                                  x: 65.50,
                                  y: 437.00,
                                  z: 0,
                                  child:
                                      GeneratedBrandicofacebookrectWidget6()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 55.0,
                              child: TransformHelper.translate(
                                  x: -7.50,
                                  y: 437.00,
                                  z: 0,
                                  child:
                                      GeneratedBrandicoinstagramfilledWidget6()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 60.0,
                              child: TransformHelper.translate(
                                  x: -79.00,
                                  y: 436.50,
                                  z: 0,
                                  child:
                                      GeneratedFabrandstwittersquareWidget6()),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 853.0,
                              right: 123.0,
                              bottom: null,
                              width: null,
                              height: 20.0,
                              child: GeneratedConnectwithusWidget6(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 789.0,
                              right: 281.0,
                              bottom: null,
                              width: null,
                              height: 23.0,
                              child: GeneratedContactWidget6(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 789.0,
                              right: 151.0,
                              bottom: null,
                              width: null,
                              height: 20.0,
                              child: Generated919015458338Widget6(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 56.0,
                              child: TransformHelper.translate(
                                  x: -147.50,
                                  y: 434.50,
                                  z: 0,
                                  child:
                                      GeneratedKooBlackIcon300x300Copy1Widget6()),
                            ),
                            Positioned(
                              left: -4.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 357.0002136230469,
                              height: 22.11505126953125,
                              child: GeneratedFrame50Widget2(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 65.0,
                              child: TransformHelper.translate(
                                  x: -2.50,
                                  y: -428.00,
                                  z: 0,
                                  child: GeneratedIITmandi29Widget()),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
