import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox83widget/generated/GeneratedOpenExternalLinkWidget1.dart';

/* Frame iPhone 11 Pro / X - 83
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX83Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 125.0,
                top: 302.0,
                right: 123.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: GeneratedOpenExternalLinkWidget1(),
              )
            ]),
      ),
    ));
  }
}
