import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedAboutUsWidget9.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedHomeWidget34.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedTeamWidget12.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedRectangle1Widget37.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedFeedbackWidget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedBrandicofacebookrectWidget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedProgrammesWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedNMICPSWidget12.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedWorkshopsWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedConnectwithusWidget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedTrainingsWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedRectangle34Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedBrandicolinkedinrectWidget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedKooBlackIcon300x300Copy1Widget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedCarbonoverflowmenuverticalWidget29.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedRectangle2Widget9.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedFabrandstwittersquareWidget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedProgrammesWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedContactUsWidget9.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedAkariconscirclechevronleftfillWidget9.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedTrainingsWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedBrandicoinstagramfilledWidget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/Generated919015458338Widget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedWorkshopsWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedTechWidget27.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox78widget/generated/GeneratedContactWidget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame iPhone 11 Pro / X - 78
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX78Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.048;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget37(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 20.0,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedCarbonoverflowmenuverticalWidget29(),
              ),
              Positioned(
                left: 0.0,
                top: 643.0,
                right: -6.0,
                bottom: null,
                width: null,
                height: 312.0,
                child: GeneratedRectangle2Widget9(),
              ),
              Positioned(
                left: 31.0,
                top: 289.0,
                right: 115.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedTrainingsWidget3(),
              ),
              Positioned(
                left: 31.0,
                top: 348.0,
                right: 115.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedProgrammesWidget3(),
              ),
              Positioned(
                left: 31.0,
                top: 219.0,
                right: 115.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedWorkshopsWidget3(),
              ),
              Positioned(
                left: 132.0,
                top: 151.0,
                right: 127.0,
                bottom: null,
                width: null,
                height: 40.0,
                child: GeneratedTechWidget27(),
              ),
              Positioned(
                left: 17.0,
                top: 673.0,
                right: 15.0,
                bottom: null,
                width: null,
                height: 92.0,
                child:
                    GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK8(),
              ),
              Positioned(
                left: 297.0,
                top: 885.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 55.0,
                child: GeneratedBrandicolinkedinrectWidget8(),
              ),
              Positioned(
                left: 224.0,
                top: 888.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 51.0,
                child: GeneratedBrandicofacebookrectWidget8(),
              ),
              Positioned(
                left: 156.0,
                top: 886.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 55.0,
                child: GeneratedBrandicoinstagramfilledWidget8(),
              ),
              Positioned(
                left: 84.0,
                top: 883.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 60.0,
                child: GeneratedFabrandstwittersquareWidget8(),
              ),
              Positioned(
                left: 120.0,
                top: 852.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 23.0,
                child: GeneratedConnectwithusWidget8(),
              ),
              Positioned(
                left: 24.0,
                top: 788.0,
                right: 287.0,
                bottom: null,
                width: null,
                height: 23.0,
                child: GeneratedContactWidget8(),
              ),
              Positioned(
                left: 107.0,
                top: 788.0,
                right: 150.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: Generated919015458338Widget8(),
              ),
              Positioned(
                left: 17.0,
                top: 883.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 56.0,
                child: GeneratedKooBlackIcon300x300Copy1Widget8(),
              ),
              Positioned(
                left: 32.0,
                top: 288.0,
                right: 114.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedTrainingsWidget4(),
              ),
              Positioned(
                left: 32.0,
                top: 347.0,
                right: 114.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedProgrammesWidget4(),
              ),
              Positioned(
                left: 32.0,
                top: 218.0,
                right: 114.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedWorkshopsWidget4(),
              ),
              Positioned(
                left: 1.0,
                top: 87.0,
                right: 141.0,
                bottom: null,
                width: null,
                height: 725.0,
                child: GeneratedRectangle34Widget1(),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: 163.0,
                bottom: 0.0,
                width: 50.0,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.17118226600985223,
                        z: 0,
                        child: Container(
                          height: height,
                          child:
                              GeneratedAkariconscirclechevronleftfillWidget9(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 25.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 28.0,
                child: GeneratedHomeWidget34(),
              ),
              Positioned(
                left: 23.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 25.0,
                child: GeneratedAboutUsWidget9(),
              ),
              Positioned(
                left: 23.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 28.0,
                child: GeneratedNMICPSWidget12(),
              ),
              Positioned(
                left: 19.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 25.0,
                child: GeneratedContactUsWidget9(),
              ),
              Positioned(
                left: 24.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 28.0,
                child: GeneratedFeedbackWidget10(),
              ),
              Positioned(
                left: 32.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 28.0,
                child: GeneratedTeamWidget12(),
              )
            ]),
      ),
    ));
  }
}
