import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox105widget/generated/GeneratedVerifyWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox105widget/generated/GeneratedRectangle1Widget49.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox105widget/generated/GeneratedEnterOTPWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox105widget/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox105widget/generated/GeneratedOTPWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox105widget/generated/GeneratedResendOTPWidget1.dart';

/* Frame iPhone 11 Pro / X - 105
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX105Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 103.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 42.0,
                child: GeneratedRectangle1Widget49(),
              ),
              Positioned(
                left: 151.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 39.0,
                child: GeneratedVerifyWidget1(),
              ),
              Positioned(
                left: 47.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 23.0,
                child: GeneratedEnterOTPWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 33.0,
                child: GeneratedRectangle22Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 186.0,
                height: 26.0,
                child: GeneratedOTPWidget1(),
              ),
              Positioned(
                left: 141.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 20.0,
                child: GeneratedResendOTPWidget1(),
              )
            ]),
      ),
    ));
  }
}
