import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox10widget/generated/GeneratedIITmandi6Widget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox10widget/generated/GeneratedFrame48Widget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox10widget/generated/GeneratedRectangle1Widget26.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox10widget/generated/GeneratedFrame49Widget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox10widget/generated/GeneratedBytesizemenuWidget20.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox10widget/generated/GeneratedCarbonoverflowmenuverticalWidget21.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame iPhone 11 Pro / X - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 955.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 955.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 0, 0, 0),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 92.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0613333333333332;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * -0.016,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedRectangle1Widget26(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 33.0,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 36.0,
                              child: GeneratedBytesizemenuWidget20(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 196.0,
                              right: -58.0,
                              bottom: null,
                              width: null,
                              height: 593.0,
                              child: GeneratedFrame48Widget3(),
                            ),
                            Positioned(
                              left: null,
                              top: 20.0,
                              right: 11.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child:
                                  GeneratedCarbonoverflowmenuverticalWidget21(),
                            ),
                            Positioned(
                              left: -4.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 357.0002136230469,
                              height: 22.11505126953125,
                              child: GeneratedFrame49Widget3(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 65.0,
                              child: TransformHelper.translate(
                                  x: -2.50,
                                  y: -428.00,
                                  z: 0,
                                  child: GeneratedIITmandi6Widget()),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
