import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedContactWidget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedSkillingWidget27.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedNMICPSWidget13.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedCarbonoverflowmenuverticalWidget30.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedFeedbackWidget11.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedBrandicolinkedinrectWidget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/Generated919015458338Widget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedProgrammesWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedKooBlackIcon300x300Copy1Widget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedConnectwithusWidget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedRectangle2Widget11.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedTeamWidget13.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedAboutUsWidget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedFabrandstwittersquareWidget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedTrainingsWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedRectangle33Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedHomeWidget35.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedBrandicoinstagramfilledWidget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedWorkshopsWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedAkariconscirclechevronleftfillWidget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedBrandicofacebookrectWidget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedContactUsWidget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox73widget/generated/GeneratedRectangle1Widget39.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame iPhone 11 Pro / X - 73
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX73Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.016;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget39(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 20.0,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedCarbonoverflowmenuverticalWidget30(),
              ),
              Positioned(
                left: 0.0,
                top: 643.0,
                right: -6.0,
                bottom: null,
                width: null,
                height: 312.0,
                child: GeneratedRectangle2Widget11(),
              ),
              Positioned(
                left: 31.0,
                top: 289.0,
                right: 115.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedTrainingsWidget6(),
              ),
              Positioned(
                left: 31.0,
                top: 348.0,
                right: 115.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedProgrammesWidget6(),
              ),
              Positioned(
                left: 31.0,
                top: 219.0,
                right: 115.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedWorkshopsWidget6(),
              ),
              Positioned(
                left: 132.0,
                top: 151.0,
                right: 127.0,
                bottom: null,
                width: null,
                height: 40.0,
                child: GeneratedSkillingWidget27(),
              ),
              Positioned(
                left: 17.0,
                top: 673.0,
                right: 51.0,
                bottom: null,
                width: null,
                height: 110.0,
                child:
                    GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK10(),
              ),
              Positioned(
                left: 297.0,
                top: 885.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 55.0,
                child: GeneratedBrandicolinkedinrectWidget10(),
              ),
              Positioned(
                left: 224.0,
                top: 888.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 51.0,
                child: GeneratedBrandicofacebookrectWidget10(),
              ),
              Positioned(
                left: 156.0,
                top: 886.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 55.0,
                child: GeneratedBrandicoinstagramfilledWidget10(),
              ),
              Positioned(
                left: 84.0,
                top: 883.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 60.0,
                child: GeneratedFabrandstwittersquareWidget10(),
              ),
              Positioned(
                left: 120.0,
                top: 852.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 23.0,
                child: GeneratedConnectwithusWidget10(),
              ),
              Positioned(
                left: 24.0,
                top: 788.0,
                right: 287.0,
                bottom: null,
                width: null,
                height: 23.0,
                child: GeneratedContactWidget10(),
              ),
              Positioned(
                left: 107.0,
                top: 788.0,
                right: 150.0,
                bottom: null,
                width: null,
                height: 20.0,
                child: Generated919015458338Widget10(),
              ),
              Positioned(
                left: 17.0,
                top: 883.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 56.0,
                child: GeneratedKooBlackIcon300x300Copy1Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 87.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 725.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6213333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle33Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: 164.0,
                bottom: 0.0,
                width: 50.0,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.1724137931034483,
                        z: 0,
                        child: Container(
                          height: height,
                          child:
                              GeneratedAkariconscirclechevronleftfillWidget10(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 31.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 28.0,
                child: GeneratedHomeWidget35(),
              ),
              Positioned(
                left: 31.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 25.0,
                child: GeneratedAboutUsWidget10(),
              ),
              Positioned(
                left: 31.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 28.0,
                child: GeneratedNMICPSWidget13(),
              ),
              Positioned(
                left: 31.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 25.0,
                child: GeneratedContactUsWidget10(),
              ),
              Positioned(
                left: 31.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 28.0,
                child: GeneratedFeedbackWidget11(),
              ),
              Positioned(
                left: 31.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 28.0,
                child: GeneratedTeamWidget13(),
              )
            ]),
      ),
    ));
  }
}
