import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/Generated3IITMandiiHubandHCIFoundationsignwiderangingMoUwithNeur4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedFrame50Widget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedIonchevronbackcircleWidget11.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedIITMandiCatalysthaslaunchedincubationprogramstodevelops4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedwwwihubiitmandiinWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedAndIndiahavesignedawiderangingMoUtoharnesseachothersstr4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedwwwrubiscapeioWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedNeuroLeapWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedMoUWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedMediaCoverageWidget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/Generated2IITMandiiHubHCIFoundationandITRACoLtdJapansignMoUWidge3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdsignMoU3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedItra1Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedToestablishstronglinkageswithnationalandinternationalor3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedITRACoLtdHeadquartersJapanTokyoRepresentativeDirectorKa3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/Generated4IITMandiiHubandHCIFoundationsignedMoUwithIITMandiCatal4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedIonchevronbackcircleWidget12.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedCarbonoverflowmenuverticalWidget9.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedIITMandiiHubHCIFoundationiHubWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedHttpswwwiitmandiacinTIHHCIannoucementsphpWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedLinkhttpsdocsgooglecomspreadsheetsd1vp_ZtdmPoa2qDWwzcX03.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedITRAWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedIITmandi14Widget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedRectangle1Widget11.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedBytesizemenuWidget9.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox69widget/generated/GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdIndiasf2.dart';

/* Frame iPhone 11 Pro / X - 69
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX69Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1583.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1583.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 0, 0, 0),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 92.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0826666666666667;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * -0.016,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedRectangle1Widget11(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 24.0,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 36.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -740.50,
                                  z: 0,
                                  child: GeneratedBytesizemenuWidget9()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: 11.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -746.50,
                                  z: 0,
                                  child:
                                      GeneratedCarbonoverflowmenuverticalWidget9()),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 1434.0,
                              right: 19.0,
                              bottom: null,
                              width: null,
                              height: 72.0,
                              child:
                                  GeneratedIITMandiCatalysthaslaunchedincubationprogramstodevelops4(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 1381.0,
                              right: 50.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  Generated4IITMandiiHubandHCIFoundationsignedMoUwithIITMandiCatal4(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 1292.0,
                              right: 23.0,
                              bottom: null,
                              width: null,
                              height: 58.0,
                              child:
                                  GeneratedAndIndiahavesignedawiderangingMoUtoharnesseachothersstr4(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 1240.0,
                              right: 53.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  Generated3IITMandiiHubandHCIFoundationsignwiderangingMoUwithNeur4(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 1145.0,
                              right: 26.0,
                              bottom: null,
                              width: null,
                              height: 86.0,
                              child:
                                  GeneratedITRACoLtdHeadquartersJapanTokyoRepresentativeDirectorKa3(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 923.0,
                              right: 62.0,
                              bottom: null,
                              width: null,
                              height: 30.0,
                              child:
                                  GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdsignMoU3(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 1098.0,
                              right: 53.0,
                              bottom: null,
                              width: null,
                              height: 30.0,
                              child:
                                  Generated2IITMandiiHubHCIFoundationandITRACoLtdJapansignMoUWidge3(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 848.0,
                              right: 28.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  GeneratedToestablishstronglinkageswithnationalandinternationalor3(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 964.0,
                              right: 26.0,
                              bottom: null,
                              width: null,
                              height: 86.0,
                              child:
                                  GeneratedIITMandiiHubHCIFoundationIndiaandRubiscapePvtLtdIndiasf2(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 794.0,
                              right: 162.0,
                              bottom: null,
                              width: null,
                              height: 28.0,
                              child: GeneratedMoUWidget3(),
                            ),
                            Positioned(
                              left: 239.0,
                              top: 963.0,
                              right: null,
                              bottom: null,
                              width: 318.0,
                              height: 55.0,
                              child: GeneratedwwwihubiitmandiinWidget2(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 1289.0,
                              right: null,
                              bottom: null,
                              width: 318.0,
                              height: 55.0,
                              child: GeneratedNeuroLeapWidget4(),
                            ),
                            Positioned(
                              left: 122.0,
                              top: 1293.0,
                              right: -62.0,
                              bottom: null,
                              width: null,
                              height: 52.0,
                              child:
                                  GeneratedIITMandiiHubHCIFoundationiHubWidget4(),
                            ),
                            Positioned(
                              left: 136.0,
                              top: 991.0,
                              right: null,
                              bottom: null,
                              width: 318.0,
                              height: 55.0,
                              child: GeneratedwwwrubiscapeioWidget2(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 711.0,
                              right: 18.0,
                              bottom: null,
                              width: null,
                              height: 19.0,
                              child:
                                  GeneratedHttpswwwiitmandiacinTIHHCIannoucementsphpWidget3(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 642.0,
                              right: 25.0,
                              bottom: null,
                              width: null,
                              height: 44.0,
                              child:
                                  GeneratedLinkhttpsdocsgooglecomspreadsheetsd1vp_ZtdmPoa2qDWwzcX03(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 152.0,
                              right: 75.0,
                              bottom: null,
                              width: null,
                              height: 31.0,
                              child: GeneratedMediaCoverageWidget5(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 250.0,
                              child: TransformHelper.translate(
                                  x: -1.00,
                                  y: -453.50,
                                  z: 0,
                                  child: GeneratedItra1Widget1()),
                            ),
                            Positioned(
                              left: null,
                              top: 0.0,
                              right: null,
                              bottom: 0.0,
                              width: 193.0,
                              height: null,
                              child: TransformHelper.translate(
                                  x: -11.00,
                                  y: 0.00,
                                  z: 0,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double height =
                                        constraints.maxHeight *
                                            0.03790271636133923;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                          x: 0,
                                          y: constraints.maxHeight *
                                              0.2943777637397347,
                                          z: 0,
                                          child: Container(
                                            height: height,
                                            child: GeneratedITRAWidget1(),
                                          ))
                                    ]);
                                  })),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: -49.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -406.50,
                                  z: 0,
                                  child:
                                      GeneratedIonchevronbackcircleWidget11()),
                            ),
                            Positioned(
                              left: 2.0,
                              top: 317.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIonchevronbackcircleWidget12(),
                            ),
                            Positioned(
                              left: -4.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 357.0002136230469,
                              height: 22.11505126953125,
                              child: GeneratedFrame50Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 65.0,
                              child: TransformHelper.translate(
                                  x: -2.50,
                                  y: -742.00,
                                  z: 0,
                                  child: GeneratedIITmandi14Widget()),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
