import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedFacultyFellowshipProgramWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedRecruitmentWidget14.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedRecruitmentWidget15.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedCFPWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedFrame28Widget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedAnubhavFellowshipProgramWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedBytesizemenuWidget19.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedIonchevronbackcircleWidget94.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedCallForProposalWidget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedCFP1Widget6.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedGM1Widget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedIonchevronbackcircleWidget89.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedPostDoc1Widget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedAnubhavFellowshipWidget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedRectangle1Widget25.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedIonchevronbackcircleWidget92.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedIonchevronbackcircleWidget90.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedDetailshttpsiitmandiacinacademicsfilespost20doc20fellow5.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedProjectsWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedDetailshttpsiitmandiacinadministrationadvrtadvt_GM_tih_4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedDetailshttpsiitmandiacinadministrationadvrtihub_faculty4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedIonchevronbackcircleWidget93.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedDetailshttpsiitmandiacinacademicsfilesAnubhav20Fellowsh5.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedAnubhav1Widget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedCallForProposalsWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedGeneralProjectManagerApplicationsareinvitedforthepostof4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedPostDoctoralFellowshipWidget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedHttpsiitmandiacinadministrationadvrtproposal_AI_ML_Dec24.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedPostDoctoralFellowshipsWidget4.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedRectangle30Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox39widget/generated/GeneratedIonchevronbackcircleWidget91.dart';

/* Frame iPhone 11 Pro / X - 39
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX39Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0506666666666666;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget25(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: GeneratedBytesizemenuWidget19(),
              ),
              Positioned(
                left: 34.0,
                top: 1027.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedFacultyFellowshipProgramWidget4(),
              ),
              Positioned(
                left: 43.0,
                top: 1114.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedPostDoctoralFellowshipsWidget4(),
              ),
              Positioned(
                left: 39.0,
                top: 1061.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedDetailshttpsiitmandiacinadministrationadvrtihub_faculty4(),
              ),
              Positioned(
                left: 109.0,
                top: 132.0,
                right: 122.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedRecruitmentWidget14(),
              ),
              Positioned(
                left: 34.0,
                top: 773.0,
                right: 26.0,
                bottom: null,
                width: null,
                height: 67.0,
                child:
                    GeneratedGeneralProjectManagerApplicationsareinvitedforthepostof4(),
              ),
              Positioned(
                left: 34.0,
                top: 864.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 59.0,
                child:
                    GeneratedDetailshttpsiitmandiacinadministrationadvrtadvt_GM_tih_4(),
              ),
              Positioned(
                left: 88.0,
                top: 941.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 40.0,
                child: GeneratedProjectsWidget4(),
              ),
              Positioned(
                left: 44.0,
                top: 1143.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedDetailshttpsiitmandiacinacademicsfilespost20doc20fellow5(),
              ),
              Positioned(
                left: 47.0,
                top: 1196.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedAnubhavFellowshipProgramWidget4(),
              ),
              Positioned(
                left: 47.0,
                top: 1228.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child:
                    GeneratedDetailshttpsiitmandiacinacademicsfilesAnubhav20Fellowsh5(),
              ),
              Positioned(
                left: 128.0,
                top: 1306.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 40.0,
                child: GeneratedCFPWidget4(),
              ),
              Positioned(
                left: 47.0,
                top: 1366.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedCallForProposalsWidget4(),
              ),
              Positioned(
                left: 47.0,
                top: 1393.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 55.0,
                child:
                    GeneratedHttpsiitmandiacinadministrationadvrtproposal_AI_ML_Dec24(),
              ),
              Positioned(
                left: 1296.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 508.0,
                child: GeneratedCFP1Widget6(),
              ),
              Positioned(
                left: 843.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 199.0,
                child: GeneratedAnubhav1Widget8(),
              ),
              Positioned(
                left: 416.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 198.0,
                child: GeneratedPostDoc1Widget8(),
              ),
              Positioned(
                left: 150.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 31.0,
                child: GeneratedRecruitmentWidget15(),
              ),
              Positioned(
                left: 536.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 28.0,
                child: GeneratedPostDoctoralFellowshipWidget8(),
              ),
              Positioned(
                left: 973.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 28.0,
                child: GeneratedAnubhavFellowshipWidget8(),
              ),
              Positioned(
                left: 1439.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 28.0,
                child: GeneratedCallForProposalWidget6(),
              ),
              Positioned(
                left: -25.0,
                top: 225.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 227.0,
                child: GeneratedGM1Widget8(),
              ),
              Positioned(
                left: 1300.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget89(),
              ),
              Positioned(
                left: 810.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget90(),
              ),
              Positioned(
                left: 416.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget91(),
              ),
              Positioned(
                left: 375.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget92(),
              ),
              Positioned(
                left: 791.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget93(),
              ),
              Positioned(
                left: 1218.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedIonchevronbackcircleWidget94(),
              ),
              Positioned(
                left: 0.0,
                top: 87.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 721.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7573333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.248,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle30Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 110.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 694.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.84;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2693333333333333,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedFrame28Widget4(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
