import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedImage12Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedAboutUsWidget7.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedNMICPSisacomprehensiveMissionaimedatcompleteconvergence1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedTeamWidget7.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedCarbonoverflowmenuverticalWidget22.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedHomeWidget26.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedNationalMissiononInterdisciplinaryCyberPhysicalSystemsN1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedTeamhttpsnmicpsgovinHomeICPSNMHOMEMGBWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedRectangle1Widget27.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedNMICPSWidget9.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedNMICPSWidget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedFeedbackWidget7.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedFormorehttpsnmicpsgovinHomeICPSNMHOMEAboutusWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedRectangle31Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedContactUsWidget7.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedAkariconscirclechevronleftfillWidget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox50widget/generated/GeneratedMinistryofScienceTechnologyDeartmentofScienceTechnology1.dart';

/* Frame iPhone 11 Pro / X - 50
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX50Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 120.0,
                top: 139.0,
                right: 67.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: GeneratedNMICPSWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.056;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016000001271565756,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget27(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 320.0,
                right: 36.0,
                bottom: null,
                width: null,
                height: 275.0,
                child:
                    GeneratedNMICPSisacomprehensiveMissionaimedatcompleteconvergence1(),
              ),
              Positioned(
                left: 30.0,
                top: 650.0,
                right: 30.0,
                bottom: null,
                width: null,
                height: 15.0,
                child:
                    GeneratedFormorehttpsnmicpsgovinHomeICPSNMHOMEAboutusWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 706.0,
                right: 30.0,
                bottom: null,
                width: null,
                height: 52.0,
                child: GeneratedTeamhttpsnmicpsgovinHomeICPSNMHOMEMGBWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 273.0,
                right: -60.0,
                bottom: null,
                width: null,
                height: 14.0,
                child:
                    GeneratedNationalMissiononInterdisciplinaryCyberPhysicalSystemsN1(),
              ),
              Positioned(
                left: 24.0,
                top: 284.0,
                right: 30.0,
                bottom: null,
                width: null,
                height: 26.0,
                child:
                    GeneratedMinistryofScienceTechnologyDeartmentofScienceTechnology1(),
              ),
              Positioned(
                left: 149.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 74.0,
                child: GeneratedImage12Widget1(),
              ),
              Positioned(
                left: null,
                top: 20.0,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedCarbonoverflowmenuverticalWidget22(),
              ),
              Positioned(
                left: 0.0,
                top: 87.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 725.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6213333333333333;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle31Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: 160.0,
                bottom: 0.0,
                width: 50.0,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.17118226600985223,
                        z: 0,
                        child: Container(
                          height: height,
                          child:
                              GeneratedAkariconscirclechevronleftfillWidget7(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 25.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 34.0,
                child: GeneratedHomeWidget26(),
              ),
              Positioned(
                left: 23.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 30.999969482421875,
                child: GeneratedAboutUsWidget7(),
              ),
              Positioned(
                left: 23.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 34.0,
                child: GeneratedNMICPSWidget9(),
              ),
              Positioned(
                left: 19.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 31.000030517578125,
                child: GeneratedContactUsWidget7(),
              ),
              Positioned(
                left: 24.0,
                top: 421.99993896484375,
                right: null,
                bottom: null,
                width: 113.0,
                height: 34.00006103515625,
                child: GeneratedFeedbackWidget7(),
              ),
              Positioned(
                left: 32.0,
                top: 464.00006103515625,
                right: null,
                bottom: null,
                width: 68.0,
                height: 33.99993896484375,
                child: GeneratedTeamWidget7(),
              )
            ]),
      ),
    ));
  }
}
