import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox85widget/generated/GeneratedTeenyiconsmessageticksolidWidget.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox85widget/generated/GeneratedThankyouforyourfeedbackWidget.dart';

/* Frame iPhone 11 Pro / X - 85
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX85Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 129.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 116.0,
                child: GeneratedTeenyiconsmessageticksolidWidget(),
              ),
              Positioned(
                left: 97.0,
                top: 358.0,
                right: 95.0,
                bottom: null,
                width: null,
                height: 18.0,
                child: GeneratedThankyouforyourfeedbackWidget(),
              )
            ]),
      ),
    ));
  }
}
