import 'package:flutter/material.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedImage2Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedBrandicoinstagramfilledWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedFeedbackWidget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedTeamWidget10.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedAppDevelopersWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedEmailceoihubiitmandiinWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedConnectwithusWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedAkariconscirclechevronleftfillWidget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedGiveusyourfeedbackhereWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedImage4Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedChiefExecutiveOfficerWidget3.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedContactWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedKooBlackIcon300x300Copy1Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedHomeWidget29.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedNMICPSWidget11.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedEmaildollychoudhary220gmailcomWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedFrame52Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedBrandicofacebookrectWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedAboutUsWidget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedBrandicolinkedinrectWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/Generated919015458338Widget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedContactUsWidget8.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedFabrandstwittersquareWidget1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK1.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedRectangle1Widget30.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedMrAvinashPunekarCEOIITMandiiHubandHCIFoundationWidget2.dart';
import 'package:flutterapp/mopoapp/generatediphone11prox51widget/generated/GeneratedCarbonoverflowmenuverticalWidget24.dart';

/* Frame iPhone 11 Pro / X - 51
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX51Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 27.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedAppDevelopersWidget1(),
              ),
              Positioned(
                left: -4.0,
                top: 120.0,
                right: -140.0,
                bottom: null,
                width: null,
                height: 813.0,
                child: GeneratedFrame52Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0586666666666666;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.015999998728434245,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget30(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: 20.0,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedCarbonoverflowmenuverticalWidget24(),
              ),
              Positioned(
                left: -3.0,
                top: 1214.0,
                right: null,
                bottom: null,
                width: 381.0,
                height: 312.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 23.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 31.0,
                child: GeneratedChiefExecutiveOfficerWidget3(),
              ),
              Positioned(
                left: 24.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 35.0,
                child:
                    GeneratedMrAvinashPunekarCEOIITMandiiHubandHCIFoundationWidget2(),
              ),
              Positioned(
                left: 26.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 52.0,
                child: GeneratedEmailceoihubiitmandiinWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 1008.0,
                right: null,
                bottom: null,
                width: 368.0,
                height: 37.0,
                child: GeneratedGiveusyourfeedbackhereWidget1(),
              ),
              Positioned(
                left: 17.0,
                top: 1233.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 60.0,
                child:
                    GeneratedAddressTIHHCIOfficeIndianInstituteofTechnologyMandiVPOK1(),
              ),
              Positioned(
                left: 17.0,
                top: 836.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 84.0,
                child: GeneratedImage2Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 642.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 83.0,
                child: GeneratedImage4Widget1(),
              ),
              Positioned(
                left: 294.0,
                top: 1456.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 55.0,
                child: GeneratedBrandicolinkedinrectWidget1(),
              ),
              Positioned(
                left: 221.0,
                top: 1459.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 51.0,
                child: GeneratedBrandicofacebookrectWidget1(),
              ),
              Positioned(
                left: 153.0,
                top: 1457.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 55.0,
                child: GeneratedBrandicoinstagramfilledWidget1(),
              ),
              Positioned(
                left: 81.0,
                top: 1454.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 60.0,
                child: GeneratedFabrandstwittersquareWidget1(),
              ),
              Positioned(
                left: 117.0,
                top: 1423.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 23.0,
                child: GeneratedConnectwithusWidget1(),
              ),
              Positioned(
                left: 15.0,
                top: 1359.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 26.0,
                child: GeneratedContactWidget1(),
              ),
              Positioned(
                left: 93.0,
                top: 1359.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 23.0,
                child: Generated919015458338Widget1(),
              ),
              Positioned(
                left: 14.0,
                top: 1454.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 56.0,
                child: GeneratedKooBlackIcon300x300Copy1Widget1(),
              ),
              Positioned(
                left: 189.0,
                top: 885.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 52.0,
                child: GeneratedEmaildollychoudhary220gmailcomWidget2(),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: 160.0,
                bottom: 0.0,
                width: 50.0,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double height =
                      constraints.maxHeight * 0.06157635467980296;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.17118226600985223,
                        z: 0,
                        child: Container(
                          height: height,
                          child:
                              GeneratedAkariconscirclechevronleftfillWidget8(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 25.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 28.0,
                child: GeneratedHomeWidget29(),
              ),
              Positioned(
                left: 23.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 25.0,
                child: GeneratedAboutUsWidget8(),
              ),
              Positioned(
                left: 23.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 28.0,
                child: GeneratedNMICPSWidget11(),
              ),
              Positioned(
                left: 19.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 25.0,
                child: GeneratedContactUsWidget8(),
              ),
              Positioned(
                left: 24.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 28.0,
                child: GeneratedFeedbackWidget8(),
              ),
              Positioned(
                left: 32.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 28.0,
                child: GeneratedTeamWidget10(),
              )
            ]),
      ),
    ));
  }
}
